### ISSUE TITLE
../mutagen: 1: ../mutagen: Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by scne** [havoc-io/homebrew-mutagen#1]
Hi there,

I'm installing mutagen on my vps with UBUNTU 18.04 but I get this error

```
claudio@shopping-instance:~$ brew install havoc-io/mutagen/mutagen
==> Installing mutagen from havoc-io/mutagen
==> Downloading https://github.com/havoc-io/mutagen/releases/download/v0.8.3/mutagen_darwin_amd64_v0.8.3.tar.gz
Already downloaded: /home/claudio/.cache/Homebrew/downloads/883129ae7f297c5a983051b0d642d6c6c03708e6cccb95b3155bd3de2e40058f--mutagen_darwin_amd64_v0.8.3.tar.gz
==> ../mutagen generate --bash-completion-script=mutagen
Last 15 lines from /home/claudio/.cache/Homebrew/Logs/mutagen/01.mutagen:
2019-05-25 11:27:26 +0200

../mutagen
generate
--bash-completion-script=mutagen

../mutagen: 1: ../mutagen: Syntax error: Unterminated quoted string

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/havoc-io/homebrew-mutagen/issues
```

suggestions?

**Comment by donnykurnia** [comment]
I also had this error message. I think this is because linux brew download darwin version of mutagen instead of linux version. Is there any way to make the linuxbrew knew that for linux system, download the linux version instead of macos version?

**Comment by xenoscopic** [comment]
Hey, sorry for the super slow reply, I'm traveling at the moment.

This is definitely due to the binaries being macOS-specific.  This formula was set up before Homebrew's Linux support became official.

I think this can be worked around using some of Homebrew's platform detection variables (which aren't really documented but can be seen in other formulae).  I'll play with this and see if I can't get it working.

**Comment by xenoscopic** [comment]
This should be fixed now, sorry for the inconvenience.  Please let me know if you run into any additional trouble with the formula.
